id: socket-lamp

display:
  title: "&9&lSocket Lamp"
  description:
    - "&r&r&7When lit remotely, emits &bend-rod&7 particles."
    - "&r&r&7Brightness scales with configured light level."
    - "&r&r&7Pairs with lamp dimmer item."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png
  fallback: lamp

model:
  type: "block_display"
  mode: "auto"


behavior:
  sounds:
    place: BLOCK_AMETHYST_BLOCK_CHIME
custom_data:
  defaultLight: 15
