id: pocket-dimension-cache

display:
  title: "&e&lPocket Dimension Cache"
  description:
    - "&r&r&7&eOpen&7 for extra-dimensional storage."
    - "&r&r&7Up to &f3 rows&7 of inventory (configurable)."
    - "&r&r&7Personal stash independent of chunk."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png
  fallback: minecraft:chest

model:
  type: "block_display"
  mode: "auto"


behavior:
  sounds:
    place: BLOCK_METAL_PLACE
custom_data:
  storageRows: 3
