id: chicken-coop-cache

display:
  title: "&aChicken Coop Cache"
  description:
    - "&7&eOpen&7 to access egg storage."
    - "&7Auto-collects eggs from nearby chickens."
    - "&7Also scoops dropped eggs into inventory."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png

model:
  type: "block_display"
  mode: "auto"


behavior:
  sounds:
    place: BLOCK_METAL_PLACE
custom_data:
  coopRadius: 6.0
  tickPeriod: 100
