id: honey-centrifuge

display:
  title: "&aHoney Centrifuge"
  description:
    - "&7Dripping-&bhoney&7 particles and slide sound."
    - "&7Ambient &bhoney&7 processing station."
    - "&7Decorative beekeeping equipment."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png
  fallback: hay

model:
  type: "block_display"
  mode: "auto"


behavior:
  sounds:
    place: BLOCK_AMETHYST_BLOCK_CHIME
custom_data:
  honeyParticles: 10
  tickPeriod: 20
