id: miners-lunch

display:
  title: "&eMiner's Lunch"
  description:
    - "&7Eat for &eHaste&7 and &6Saturation II&7."
    - "&760 seconds of mining speed and food fill."
    - "&7Consumable with cooldown."

item:
  base_material: paper

textures:
  icon: icon.png
  fallback: potion

behavior:
  right_click_air: use
  right_click_block: use

custom_data:
  cooldownTicks: 12000
