id: milking-station

display:
  title: "&aMilking Station"
  description:
    - "&7Detects passive mobs within &f3 blocks&7."
    - "&7Honey-drip particles and cow-milk sound."
    - "&7Ambient auto-milking station."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png

model:
  type: "block_display"
  mode: "auto"


behavior:
  sounds:
    place: BLOCK_AMETHYST_BLOCK_CHIME
custom_data:
  tickPeriod: 20
