id: moss-creeper

display:
  title: "&aMoss Creeper"
  description:
    - "&7Spreads moss on blocks near water."
    - "&f3-block&7 radius mossification each tick."
    - "&7&bPassive&7 biome-greening block."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png
  fallback: hay

model:
  type: "block_display"
  mode: "auto"


behavior:
  sounds:
    place: BLOCK_AMETHYST_BLOCK_CHIME
custom_data:
  mossRadius: 3
  tickPeriod: 20
