id: ouija-slab

display:
  title: "&dOuija Slab"
  description:
    - "&7It only speaks when others &dgather&7 round."
    - "&7Stand at its corners and listen."
    - "&7The letters know more than they should."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png

model:
  type: "block_display"
  mode: "auto"


behavior:
  sounds:
    place: BLOCK_AMETHYST_BLOCK_CHIME
custom_data:
  minPlayers: 2
  tickPeriod: 30
