id: timed-charge

display:
  title: "&6&lTimed Charge"
  description:
    - "&r&r&7Place it, then link a &edetonator&7."
    - "&r&r&7Cannot be lit with &fflint and steel&7."
    - "&r&r&7&eRight-click&7 the &fdetonator&7 to blow it remotely."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png
  fallback: redstone

model:
  type: "block_display"
  mode: "auto"

behavior:
  combustible: false
  left_click_block: none
  right_click_block: none
  sounds:
    place: BLOCK_TNT_PLACE

custom_data:
  fuse: 100
  power: 4.0
  fire: false
  blockDamage: true
