id: player-chronicle-book

display:
  title: "&bPlayer Chronicle Book"
  description:
    - "&7Right-click to use the player chronicle book."
    - "&7Check the effect after use."

item:
  base_material: paper

textures:
  icon: icon.png

behavior:
  right_click_air: use
  right_click_block: use
