id: scarecrow-anchor

display:
  title: "&bScarecrow Anchor"
  description:
    - "&7Pushes hostile mobs away from the anchor."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png

model:
  type: "block_display"
  mode: "auto"


behavior:
  sounds:
    place: BLOCK_AMETHYST_BLOCK_CHIME
custom_data:
  scareRadius: 8.0
  tickPeriod: 20
