id: swap-charge

display:
  title: "&c&lSwap Charge"
  description:
    - "&r&r&7Place and ignite with &fflint and steel&7 or &6fire charge&7."
    - "&r&r&7Fuses for &e2.5s&7, then swaps nearby players on detonation."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png
  fallback: minecraft:tnt

model:
  type: "block_display"
  mode: "auto"


behavior:
  combustible: true
  ignition_materials:
    - FLINT_AND_STEEL
    - FIRE_CHARGE
  sounds:
    place: BLOCK_TNT_PLACE
    ignite: ITEM_FLINTANDSTEEL_USE
custom_data:
  fuse: 50
  power: 2.5
  swapRadius: 8.0
  tickInterval: 5
