id: sandblaster

display:
  title: "&6&lSandblaster"
  description:
    - "&r&r&7Etch &fstone&7 into &7chiseled stone bricks&7."
    - "&r&r&7Affects blocks in a small radius around target."
    - "&r&r&7Consumes one charge per blast."

item:
  base_material: paper

textures:
  icon: icon.png
  fallback: tool

behavior:
  right_click_air: use
  right_click_block: use

custom_data:
  etchRadius: 1
