id: spice-rack

display:
  title: "&6Spice Rack"
  description:
    - "&7Open to season food with spices."
    - "&7Food + spice grants &eHaste&7 and brief &6Saturation&7."
    - "&7Seasoning station for kitchen builds."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png

model:
  type: "block_display"
  mode: "auto"


behavior:
  sounds:
    place: BLOCK_METAL_PLACE
