id: piglin-barter-post

display:
  title: "&6Piglin Barter Post"
  description:
    - "&7Open GUI: insert a &6gold ingot&7."
    - "&7Trades for random nether loot (pearls, crying obsidian, etc.)."
    - "&7Piglin admiring sound on barter."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png

model:
  type: "block_display"
  mode: "auto"


behavior:
  sounds:
    place: BLOCK_METAL_PLACE
custom_data:
  tickPeriod: 30
