id: scaffold-charge

display:
  title: "&bScaffold Charge"
  description:
    - "&7Builds upward scaffolding, then detonates."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png

model:
  type: "block_display"
  mode: "auto"


behavior:
  combustible: true
  ignition_materials:
    - FLINT_AND_STEEL
    - FIRE_CHARGE
  sounds:
    place: BLOCK_TNT_PLACE
    ignite: ITEM_FLINTANDSTEEL_USE
custom_data:
  fuse: 50
  power: 3.0
  scaffoldHeight: 4
  tickInterval: 5
