id: anti-gravity-zone

display:
  title: "&c&lAnti Gravity Zone"
  description:
    - "&r&r&7Place and ignite with &fflint and steel&7 or &6fire charge&7."
    - "&r&r&7Fuses for &e0.5s&7, then lifts entities in anti-gravity."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png
  fallback: tnt

model:
  type: "block_display"
  mode: "auto"

behavior:
  combustible: true
  left_click_block: break
  right_click_block: ignite
  ignition_materials:
    - FLINT_AND_STEEL
    - FIRE_CHARGE
  sounds:
    place: BLOCK_STONE_PLACE
    ignite: ITEM_FLINTANDSTEEL_USE

custom_data:
  fuse: 0
  power: 4.0
  fire: false
  blockDamage: true
