id: remote-c4

display:
  title: "&6Remote C4"
  description:
    - "&7Place it, then link a &edetonator&7."
    - "&7Cannot be lit with flint & steel."
    - "&7Right-click the detonator to blow it remotely."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png

model:
  type: "block_display"
  mode: "auto"

behavior:
  combustible: false
  left_click_block: none
  right_click_block: none
  sounds:
    place: BLOCK_TNT_PLACE

custom_data:
  fuse: 0
  power: 4.0
  fire: false
  blockDamage: true
