id: ricochet-tnt

display:
  title: "&cRicochet TNT"
  description:
    - "&7Place and ignite with &fflint and steel&7 or &6fire charge&7."
    - "&7Fuses for &e3.5s&7, then ricochets blasts along a path."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png

model:
  type: "block_display"
  mode: "auto"


behavior:
  combustible: true
  ignition_materials:
    - FLINT_AND_STEEL
    - FIRE_CHARGE
  sounds:
    place: BLOCK_TNT_PLACE
    ignite: ITEM_FLINTANDSTEEL_USE
custom_data:
  bounces: 4
  fuse: 70
  power: 3.0
  step: 2.5
  tickInterval: 5
