id: keyring-beacon

display:
  title: "&bKeyring Beacon"
  description:
    - "&7Right-click to use the keyring beacon."
    - "&7Check the effect after use."

item:
  base_material: paper

textures:
  icon: icon.png

behavior:
  right_click_air: use
  right_click_block: use

custom_data:
  beaconSlots: 3
