id: display-case

display:
  title: "&6&lDisplay Case"
  description:
    - "&r&r&7&eOpen&7 to place one item on display."
    - "&r&r&7Showcases a single item in &eslot &e13&7."
    - "&r&r&7Decorative trophy case."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png
  fallback: minecraft:glass

model:
  type: "block_display"
  mode: "auto"


behavior:
  sounds:
    place: BLOCK_METAL_PLACE
