id: fortune-cookie-maker

display:
  title: "&6&lFortune Cookie Maker"
  description:
    - "&r&r&7Open GUI: insert &ewheat&7 + &fpaper&7 to craft cookies."
    - "&r&r&7Hold a cookie and open for a random &6fortune&7 message."
    - "&r&r&7Fortunes warn of creepers, luck, and cruel irony."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png
  fallback: barrel

model:
  type: "block_display"
  mode: "auto"


behavior:
  sounds:
    place: BLOCK_METAL_PLACE
custom_data:
  tickPeriod: 40
