id: pizza-oven

display:
  title: "&6Pizza Oven"
  description:
    - "&7Open GUI: insert &fbread&7, &ebeetroot&7, &fmilk bucket&7."
    - "&7Bakes a &dcake&7 (pizza) with flame particles."
    - "&7Smoker smoke and lava sparkle."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png

model:
  type: "block_display"
  mode: "auto"


behavior:
  sounds:
    place: BLOCK_METAL_PLACE
custom_data:
  tickPeriod: 50
