id: pause-tnt

display:
  title: "&dPause TNT"
  description:
    - "&7The countdown &dstops&7. And waits."
    - "&7Just when you relax, time resumes."
    - "&7Patience is its cruelest trick."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png

model:
  type: "block_display"
  mode: "auto"


behavior:
  combustible: true
  ignition_materials:
    - FLINT_AND_STEEL
    - FIRE_CHARGE
  sounds:
    place: BLOCK_TNT_PLACE
    ignite: ITEM_FLINTANDSTEEL_USE
custom_data:
  fuse: 100
  pauseDuration: 20
  power: 4.5
  tickInterval: 5
