id: drying-rack

display:
  title: "&6Drying Rack"
  description:
    - "&7Emits &bcampfire&7 smoke particles."
    - "&7Wool-break ambient sound."
    - "&7Decorative food and herb drying station."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png
  fallback: smoker

model:
  type: "block_display"
  mode: "auto"


behavior:
  sounds:
    place: BLOCK_AMETHYST_BLOCK_CHIME
custom_data:
  smokeCount: 4
  tickPeriod: 20
