id: cable-ties

display:
  title: "&bCable Ties"
  description:
    - "&7Decorative particle cable between fence posts."

item:
  base_material: paper

textures:
  icon: icon.png

behavior:
  right_click_air: use
  right_click_block: use
