id: glow-ink-lantern

display:
  title: "&6&lGlow Ink Lantern"
  description:
    - "&r&r&7&bGlow-squid&7 particles and amethyst chime."
    - "&r&r&7Ambient &elight&7 decoration."
    - "&r&r&7&bPassive&7 glow while placed."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png
  fallback: lantern

model:
  type: "block_display"
  mode: "auto"


behavior:
  sounds:
    place: BLOCK_AMETHYST_BLOCK_CHIME
custom_data:
  glowCount: 6
  tickPeriod: 20
