id: glow-ink-lantern

display:
  title: "&6Glow Ink Lantern"
  description:
    - "&7Glow-squid particles and amethyst chime."
    - "&7Ambient light decoration."
    - "&7Passive glow while placed."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png

model:
  type: "block_display"
  mode: "auto"


behavior:
  sounds:
    place: BLOCK_AMETHYST_BLOCK_CHIME
custom_data:
  glowCount: 6
  tickPeriod: 20
