id: kelp-compressor

display:
  title: "&aKelp Compressor"
  description:
    - "&7Place to activate the kelp compressor."
    - "&7Runs passively while placed nearby."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png

model:
  type: "block_display"
  mode: "auto"


behavior:
  sounds:
    place: BLOCK_AMETHYST_BLOCK_CHIME
custom_data:
  kelpBubbles: 6
  tickPeriod: 20
