id: kelp-compressor

display:
  title: "&a&lKelp Compressor"
  description:
    - "&r&r&7&bBubble&7 particles and wet-grass sound."
    - "&r&r&7Ambient kelp processing station."
    - "&r&r&7Decorative underwater-farm equipment."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png
  fallback: minecraft:hay_block

model:
  type: "block_display"
  mode: "auto"


behavior:
  sounds:
    place: BLOCK_AMETHYST_BLOCK_CHIME
custom_data:
  kelpBubbles: 6
  tickPeriod: 20
