id: irrigation-sprinkler

display:
  title: "&bIrrigation Sprinkler"
  description:
    - "&7Consumes water to irrigate farmland."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png

model:
  type: "block_display"
  mode: "auto"


behavior:
  sounds:
    place: BLOCK_METAL_PLACE
custom_data:
  tickPeriod: 40
  waterRadius: 4
