id: crop-accelerator

display:
  title: "&a&lCrop Accelerator"
  description:
    - "&r&r&7Bonemeals crops in a &a4-block&7 radius each tick."
    - "&r&r&7Bone-meal sound on growth pulse."
    - "&r&r&7&bPassive&7 crop growth booster."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png
  fallback: hay

model:
  type: "block_display"
  mode: "auto"


behavior:
  sounds:
    place: BLOCK_AMETHYST_BLOCK_CHIME
custom_data:
  cropRadius: 4
  tickPeriod: 20
