id: tripwire-charge

display:
  title: "&cTripwire Charge"
  description:
    - "&7Place two charges to string a &etripwire&7 between them."
    - "&7Both ends &cdetonate&7 when something crosses the line."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png

model:
  type: "block_display"
  mode: "auto"

behavior:
  combustible: false
  left_click_block: none
  right_click_block: none
  sounds:
    place: BLOCK_TNT_PLACE

custom_data:
  fuse: 0
  power: 4.0
  fire: false
  blockDamage: true
