id: divers-salt

display:
  title: "&eDivers Salt"
  description:
    - "&7Right-click to use the divers salt."
    - "&7Check the effect after use."

item:
  base_material: paper

textures:
  icon: icon.png

behavior:
  right_click_air: use
  right_click_block: use
custom_data:
  cooldownTicks: 0
