id: picnic-basket

display:
  title: "&6&lPicnic Basket"
  description:
    - "&r&r&7Open for &f6 slots&7 of portable food storage."
    - "&r&r&7Carry snacks on the go."
    - "&r&r&7Tracks last-&eopen&7 time per block."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png
  fallback: barrel

model:
  type: "block_display"
  mode: "auto"


behavior:
  sounds:
    place: BLOCK_METAL_PLACE
