id: checkpoint-obelisk

display:
  title: "&b&lCheckpoint Obelisk"
  description:
    - "&r&r&7&eRight-click&7 to record your coordinates."
    - "&r&r&7Shows coords on the action bar."
    - "&r&r&7Totem pulse &ering&7 marks the save."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png
  fallback: minecraft:beacon

model:
  type: "block_display"
  mode: "auto"


behavior:
  sounds:
    place: BLOCK_METAL_PLACE
