id: compost-heap

display:
  title: "&aCompost Heap"
  description:
    - "&7&bComposter&7 particles and fill sound."
    - "&7Ambient composting activity while placed."
    - "&7Pairs with farming setups."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png

model:
  type: "block_display"
  mode: "auto"


behavior:
  sounds:
    place: BLOCK_AMETHYST_BLOCK_CHIME
custom_data:
  compostParticles: 5
  tickPeriod: 20
