id: infuser

display:
  title: "&6Infuser"
  description:
    - "&7&bEnchant&7 particles and high-pitch chime."
    - "&7Ambient infusion station."
    - "&7Decorative potion and flavor infuser."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png

model:
  type: "block_display"
  mode: "auto"


behavior:
  sounds:
    place: BLOCK_AMETHYST_BLOCK_CHIME
custom_data:
  infuseParticles: 8
  tickPeriod: 20
