id: luck-dust

display:
  title: "&bLuck Dust"
  description:
    - "&7Sprinkle near chest for bonus loot roll."

item:
  base_material: paper

textures:
  icon: icon.png

behavior:
  right_click_air: use
  right_click_block: use
custom_data:
  cooldownTicks: 0
