id: divers-salt

display:
  title: "&bDiver's Salt"
  description:
    - "&7Water breathing for 90 seconds."

item:
  base_material: paper

textures:
  icon: icon.png

behavior:
  right_click_air: use
  right_click_block: use
custom_data:
  cooldownTicks: 0
