id: smoke-grenade

display:
  title: "&6Smoke Grenade"
  description:
    - "&7Throwable smoke screen"

item:
  base_material: snowball

textures:
  icon: icon.png

behavior:
  right_click_air: throw
  right_click_block: throw

custom_data:
  throw_velocity: 1.2
  smokeRadius: 5.0
  smokeDuration: 120
