id: repair-station-block

display:
  title: "&6Repair Station Block"
  description:
    - "&7Right-click with a held item to repair durability."
    - "&7See item lore for usage hints."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png

model:
  type: "block_display"
  mode: "auto"


behavior:
  sounds:
    place: BLOCK_METAL_PLACE
custom_data:
  repairAmount: 25
