id: mulch-spreader

display:
  title: "&aMulch Spreader"
  description:
    - "&7Spread mulch on the block below you."
    - "&7Turns paths into &amosm blocks&7."
    - "&7Otherwise mossifies blocks near water."

item:
  base_material: paper

textures:
  icon: icon.png
  fallback: fertilizer

behavior:
  right_click_air: use
  right_click_block: use
