id: mulch-spreader

display:
  title: "&a&lMulch Spreader"
  description:
    - "&r&r&7Spread mulch on the block below you."
    - "&r&r&7Turns paths into &amosm blocks&7."
    - "&r&r&7Otherwise mossifies blocks near water."

item:
  base_material: paper

textures:
  icon: icon.png
  fallback: igniscore:fertilizer

behavior:
  right_click_air: use
  right_click_block: use
