id: atlas-imprinter

display:
  title: "&bAtlas Imprinter"
  description:
    - "&7Right-click to use the atlas imprinter."
    - "&7Check the effect after use."

item:
  base_material: paper

textures:
  icon: icon.png

behavior:
  right_click_air: use
  right_click_block: use
