id: structure-compass

display:
  title: "&bStructure Compass"
  description:
    - "&7Right-click to use the structure compass."
    - "&7Check the effect after use."

item:
  base_material: paper

textures:
  icon: icon.png

behavior:
  right_click_air: use
  right_click_block: use
