id: motion-floodlight

display:
  title: "&6Motion Floodlight"
  description:
    - "&7Scans &bend-rod&7 beams at nearby players."
    - "&f8-block&7 motion-detection radius."
    - "&7Lights up when players are near."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png

model:
  type: "block_display"
  mode: "auto"


behavior:
  sounds:
    place: BLOCK_AMETHYST_BLOCK_CHIME
custom_data:
  motionRadius: 8.0
  tickPeriod: 20
