id: lock

display:
  title: "&6Lock"
  description:
    - "&7Toggle &cengaged&7 / &adisengaged&7 on the item."
    - "&7Wax-on/wax-off particles on &etoggle&7."
    - "&7Iron &btrapdoor&7 sound feedback."

item:
  base_material: paper

textures:
  icon: icon.png
  fallback: tool

behavior:
  right_click_air: use
  right_click_block: use
