id: ice-cream-freezer

display:
  title: "&6&lIce Cream Freezer"
  description:
    - "&r&r&7Open GUI: insert &fsnow&7, &csweet berries&7, and &fmilk bucket&7."
    - "&r&r&7Outputs a &fbowl&7 of ice cream each tick."
    - "&r&r&7Cloud particles and powder-snow sound."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png
  fallback: minecraft:barrel

model:
  type: "block_display"
  mode: "auto"


behavior:
  sounds:
    place: BLOCK_METAL_PLACE
custom_data:
  tickPeriod: 60
