id: hologram-tnt

display:
  title: "&dHologram TNT"
  description:
    - "&7Is it really there? Are &dany&7 of them?"
    - "&7Copies dance while the real fuse burns."
    - "&7Seeing is no longer believing."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png

model:
  type: "block_display"
  mode: "auto"

behavior:
  combustible: true
  left_click_block: break
  right_click_block: ignite
  ignition_materials:
    - FLINT_AND_STEEL
    - FIRE_CHARGE
  sounds:
    place: BLOCK_TNT_PLACE
    ignite: ITEM_FLINTANDSTEEL_USE

custom_data:
  fuse: 80
  power: 4.0
  fire: false
  blockDamage: true
