id: keyed-hatch

display:
  title: "&9Keyed Hatch"
  description:
    - "&7&bRemote&7-controlled hatch linked to a key."
    - "&7Opens and closes with &btrapdoor&7 feedback."
    - "&7Part of the &9keyed hatch&7 network."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png
  fallback: trapdoor

model:
  type: "block_display"
  mode: "auto"


behavior:
  sounds:
    place: BLOCK_AMETHYST_BLOCK_CHIME
