id: concussion-tnt

display:
  title: "&cConcussion TNT"
  description:
    - "&7Place and ignite with flint & steel or fire charge."
    - "&7Fuses for &e3.0s&7, then hurls entities with massive knockback."

block:
  placeable: true
  breakable: true
  breaking:
    ticks: 0
    break_sound: BLOCK_GRAVEL_BREAK
    hit_sound: BLOCK_GRAVEL_HIT

textures:
  top: top.png
  side: side.png
  bottom: bottom.png

model:
  type: "block_display"
  mode: "auto"

behavior:
  combustible: true
  left_click_block: break
  right_click_block: ignite
  ignition_materials:
    - FLINT_AND_STEEL
    - FIRE_CHARGE
    - FLINT
  sounds:
    place: BLOCK_BEACON_ACTIVATE
    ignite: ITEM_FLINTANDSTEEL_USE

custom_data:
  fuse: 60
  knockbackRadius: 18.0
  knockbackStrength: 3.2
  blockDamage: false
  terrainPower: 1.5
